### ISSUE TITLE
template/retry: do not use time.After

### ISSUE THREAD

**Issue by vetcher** [hexdigest/gowrap#12]
I think, it should not be difficult to change usage of `time.After` to `time.NewTimer`.
The problem is described in docs of [time.After](https://golang.org/pkg/time/#After).
I some edge cases it should reduce memory consumption.
Because it is a template, it should not break back capability.

```go
{{range $method := .Interface.Methods}}
	{{if $method.ReturnsError}}
	// {{$method.Name}} implements {{$.Interface.Type}}
	func (_d {{$decorator}}) {{$method.Declaration}} {
		for _i := 0; _i < _d._retryCount; _i++ {
			{{$method.ResultsNames}} = _d.{{$.Interface.Name}}.{{$method.Call}}
			if err == nil {
				break
			}
			if _d._retryCount > 1 {
				{{- if $method.AcceptsContext}}
				_t := time.NewTimer(_d._retryInterval)
				defer _t.Stop()
				select {
				case <-ctx.Done():
					return {{$method.ResultsNames}}
				case <-_t.C:
				}
				{{else}}
				time.Sleep(_d._retryInterval)
				{{end -}}
			}
		}
		return {{$method.ResultsNames}}
	}
	{{end}}
{{end}}
```

**Comment by hexdigest** [comment]
Hi @vetcher ,
Thanks for the issue. The problem with timer in your example is that it will definetely lead to extra memory consumption because defer _t.Stop() is called within a loop and the timer will be closed only after decorator exits before that we will have N timer goroutines running. But I agree that this can be rewritten a bit. Stay tuned.
