### ISSUE TITLE
Unable to install this package

### ISSUE THREAD

**Issue by masv87** [hexdigest/gowrap#43]
I'm trying to install gowrap using command  `go get -u github.com/hexdigest/gowrap/cmd/gowrap`
And receiving an error: 

> go get: github.com/cavaliercoder/go-cpio@v0.0.0-20180626203310-925f9528c45e updating to
        github.com/cavaliercoder/go-cpio@v1.0.1: parsing go.mod:
        module declares its path as: github.com/cavaliergopher/cpio
                but was required as: github.com/cavaliercoder/go-cpio

**Comment by kiaplayer** [comment]
Same here. +1

**Comment by hexdigest** [comment]
@masv87 @kiaplayer @m4ex 

This was due to https://github.com/google/rpmpack/issues/69 
I fixed the issue by bumping some deps versions and also moved goreleaser and golangci-lint dependencies to a submodule, so GoWrap itself now has much less dependencies than before.

I also recommend to install GoWrap from binaries that can be found here: https://github.com/hexdigest/gowrap/releases
